### PR TITLE
Manual mode improvements (use correct event type, add new listeners)

### LINKED ISSUE #899: Manual tenancy with CreateTenantConnection throws a TypeError
### Bug description

Manually initializing Tenancy in manual mode throws an exception. The error only seems to occur on the first `$tenant->run()` call.
image

Stack trace:
(I moved the logic to a `testing()` method in the CreateTenantConnection listener so I could catch the exception in `handle()`)

```
[2022-07-18 05:49:26] local.ERROR: Stancl\Tenancy\Listeners\CreateTenantConnection::testing(): Argument #1 ($event) must be of type Stancl\Tenancy\Events\Contracts\TenantEvent, Stancl\Tenancy\Events\TenancyInitialized given, called in /Users/lukas/Projects/tenancy-test/vendor/stancl/tenancy/src/Listeners/CreateTenantConnection.php on line 23 {"exception":"[object] (TypeError(code: 0): Stancl\\Tenancy\\Listeners\\CreateTenantConnection::testing(): Argument #1 ($event) must be of type Stancl\\Tenancy\\Events\\Contracts\\TenantEvent, Stancl\\Tenancy\\Events\\TenancyInitialized given, called in /Users/lukas/Projects/tenancy-test/vendor/stancl/tenancy/src/Listeners/CreateTenantConnection.php on line 23 at /Users/lukas/Projects/tenancy-test/vendor/stancl/tenancy/src/Listeners/CreateTenantConnection.php:29)
[stacktrace]
#0 /Users/lukas/Projects/tenancy-test/vendor/stancl/tenancy/src/Listeners/CreateTenantConnection.php(23): Stancl\\Tenancy\\Listeners\\CreateTenantConnection->testing(Object(Stancl\\Tenancy\\Events\\TenancyInitialized))
#1 /Users/lukas/Projects/tenancy-test/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(441): Stancl\\Tenancy\\Listeners\\CreateTenantConnection->handle(Object(Stancl\\Tenancy\\Events\\TenancyInitialized))
#2 /Users/lukas/Projects/tenancy-test/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(249): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('Stancl\\\\Tenancy\\\\...', Array)
#3 /Users/lukas/Projects/tenancy-test/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(450): Illuminate\\Events\\Dispatcher->dispatch('Stancl\\\\Tenancy\\\\...')
#4 /Users/lukas/Projects/tenancy-test/vendor/stancl/tenancy/src/Tenancy.php(58): event(Object(Stancl\\Tenancy\\Events\\TenancyInitialized))
#5 /Users/lukas/Projects/tenancy-test/vendor/stancl/tenancy/src/Database/Concerns/TenantRun.php(23): Stancl\\Tenancy\\Tenancy->initialize(Object(App\\Models\\Tenant))
#6 /Users/lukas/Projects/tenancy-test/vendor/psy/psysh/src/ExecutionLoopClosure.php(55) : eval()'d code(1): Stancl\\Tenancy\\Database\\Models\\Tenant->run(Object(Closure))
#7 /Users/lukas/Projects/tenancy-test/vendor/psy/psysh/src/ExecutionLoopClosure.php(55): eval()
#8 /Users/lukas/Projects/tenancy-test/vendor/psy/psysh/src/ExecutionClosure.php(89): Psy\\{closure}()
#9 /Users/lukas/Projects/tenancy-test/vendor/psy/psysh/src/Shell.php(383): Psy\\ExecutionClosure->execute()
#10 /Users/lukas/Projects/tenancy-test/vendor/psy/psysh/src/Shell.php(354): Psy\\Shell->doInteractiveRun()
#11 /Users/lukas/Projects/tenancy-test/vendor/symfony/console/Application.php(171): Psy\\Shell->doRun(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Psy\\Output\\ShellOutput))
#12 /Users/lukas/Projects/tenancy-test/vendor/psy/psysh/src/Shell.php(329): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Psy\\Output\\ShellOutput))
#13 /Users/lukas/Projects/tenancy-test/vendor/laravel/tinker/src/Console/TinkerCommand.php(81): Psy\\Shell->run()
#14 /Users/lukas/Projects/tenancy-test/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\\Tinker\\Console\\TinkerCommand->handle()
#15 /Users/lukas/Projects/tenancy-test/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#16 /Users/lukas/Projects/tenancy-test/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#17 /Users/lukas/Projects/tenancy-test/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#18 /Users/lukas/Projects/tenancy-test/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#19 /Users/lukas/Projects/tenancy-test/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call(Array)
#20 /Users/lukas/Projects/tenancy-test/vendor/symfony/console/Command/Command.php(308): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#21 /Users/lukas/Projects/tenancy-test/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#22 /Users/lukas/Projects/tenancy-test/vendor/symfony/console/Application.php(998): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#23 /Users/lukas/Projects/tenancy-test/vendor/symfony/console/Application.php(299): Symfony\\Component\\Console\\Application->doRunCommand(Object(Laravel\\Tinker\\Console\\TinkerCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#24 /Users/lukas/Projects/tenancy-test/vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#25 /Users/lukas/Projects/tenancy-test/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#26 /Users/lukas/Projects/tenancy-test/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#27 /Users/lukas/Projects/tenancy-test/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#28 {main}
"} 
```

### Steps to reproduce

1. In TenancyServiceProvider, add CreateTenantConnection listener to the TenancyInitialized event, remove BootstrapTenancy:
```php
Events\TenancyInitialized::class => [
    - Listeners\BootstrapTenancy::class,
    + Listeners\CreateTenantConnection::class,
],
```

2. Create a tenant using tinker, and call `$tenant->run(fn() => 'test')`

### Expected behavior

The first `$tenant->run(fn() => 'test')` call should have returned 'test' instead of throwing the exception.

### Laravel version

9.20.0

### stancl/tenancy version

3.5.7

### PR DESCRIPTION
**Pull request by abrardev99**
closes #899 

This PR fixes the issue described in #899, which is related to initializing tenancy manually using the `CreateTenantConnection` listener. The problem was, `CreateTenantConnection` expected "TenantEvent $event" while it received `TenancyEvent`. 

PR also added the new listeners to match the automatic bootstrappers test. 

- `UseTenantConnection` listener that calls `DatabaseManager::setDefaultConnection('tenant')`
- `UseCentralConnection` listener that calls DatabaseManager::reconnectToCentral()

Also, added tests to ensure manual tenancy initialization works fine.

### CODE REVIEW

File: tests/ManualModeTest.php [hunk 1]
```diff
@@ -0,0 +1,18 @@
...
+use \Stancl\Tenancy\Tests\Etc\Tenant;
+
+test('manual tenancy initialization works', function () {
+    Event::listen(TenancyInitialized::class, CreateTenantConnection::class);
+
+    $tenant = Tenant::create();
+
+    tenancy()->initialize($tenant);
+
+    expect(tenancy()->initialized)->toBeTrue();
```
Comment (stancl) [inline tests/ManualModeTest.php]: Does this assert anything about `CreateTenantConnection`?

Comment (stancl) [reply tests/ManualModeTest.php]: Seems like it just checks that no exception is thrown. But we want to check **that it also works**.

Comment (abrardev99) [reply tests/ManualModeTest.php]: No. 
But I was confused about how to test this. I initially wrote that test without making any changes in the listener. The test was failing. When I made the change, test passed. 

So that's that. Suggest me to make it better?

Comment (stancl) [reply tests/ManualModeTest.php]: > But I was confused about how to test this

It's extremely simple. The listener does only one thing: it creates a connection. So you assert that the connection doesn't exist _before_ initializing tenancy, and assert that it does exist _after_ initializing tenancy.

When you're writing a regression test, it's not enough that an exception disappears. The test you have here, as it works now, doesn't assert **anything about the behavior that should be tested according to the test name**. It just checks that an exception isn't thrown.

**Comment by stancl** [comment]
I'm thinking that this PR should expand/fix the ability to use manual initialization in general. Instead of just fixing this one bug.

So I added a `purgeTenantConnection()` call in https://github.com/archtechx/tenancy/pull/1013/commits/fcf07e99db54908eefbea51df3fcdab20359bb5f to make it work the same way as `DatabaseManager::connectToTenant()`.

Now the only things we need, to make this event approach fully equivalent to bootstrappers, are:
- `UseTenantConnection` listener that will call `DatabaseManager::setDefaultConnection('tenant')`
- `UseCentralConnection` listener that will do the same thing as `DatabaseManager::reconnectToCentral()`

File: tests/ManualModeTest.php (hunk 1 above)
Comment (abrardev99) [reply tests/ManualModeTest.php]: > So you assert that the connection doesn't exist before initializing tenancy, and assert that it does exist after initializing tenancy.

Test updated.

**Comment by abrardev99** [comment]
> Now the only things we need, to make this event approach fully equivalent to bootstrappers, are:
>1. UseTenantConnection listener that will call DatabaseManager::setDefaultConnection('tenant')
>2. UseCentralConnection listener that will do the same thing as DatabaseManager::reconnectToCentral()

So do I need to add these? I didn't understand. Are you suggesting something or just leaving comments? @stancl

**Comment by stancl** [comment]
The PR should include them.

> I'm thinking that this PR should expand/fix the ability to use manual initialization in general

**Comment by abrardev99** [comment]
> The PR should include them.

Ok, can you please expand on this

> Now the only things we need, to make this event approach fully equivalent to bootstrappers, are:
> 
> UseTenantConnection listener that will call DatabaseManager::setDefaultConnection('tenant')
> UseCentralConnection listener that will do the same thing as DatabaseManager::reconnectToCentral()

I'm not getting what to add and how to add?

**Comment by stancl** [comment]
The two listeners I mentioned. Add them the same way `CreateTenantConnection` exists

**Comment by abrardev99** [comment]
> The two listeners I mentioned. Add them the same way `CreateTenantConnection` exists

Done

File: tests/ManualModeTest.php [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+
+    expect(app('db')->getDefaultConnection())->toBe('tenant');
+    expect(array_keys(app('db')->getConnections()))->toBe(['central', 'tenant']);
+    pest()->assertArrayHasKey('tenant', config('database.connections'));
+
+    tenancy()->end();
+
+    expect(array_keys(app('db')->getConnections()))->toBe(['central']);
+    expect(config('database.connections.tenant'))->toBeNull();
+    expect(app('db')->getDefaultConnection())->toBe(config('tenancy.database.central_connection'));
```
Comment (stancl) [inline tests/ManualModeTest.php:44]: This assertion (or the opposite of it — that the tenant connection is the default connection) should also be in the `initialize()` section.

File: tests/ManualModeTest.php [hunk 3]
```diff
@@ -0,0 +1,42 @@
...
+use Stancl\Tenancy\Jobs\CreateDatabase;
+use Stancl\Tenancy\Listeners\CreateTenantConnection;
+use Stancl\Tenancy\Listeners\UseCentralConnection;
+use Stancl\Tenancy\Listeners\UseTenantConnection;
+use \Stancl\Tenancy\Tests\Etc\Tenant;
+
+test('manual tenancy initialization works', function () {
+    Event::listen(TenantCreated::class, JobPipeline::make([CreateDatabase::class])->send(function (TenantCreated $event) {
+        return $event->tenant;
+    })->toListener());
```
Comment (stancl) [inline tests/ManualModeTest.php:19]: Do we need this? And the `createUsersTable()` call below

Comment (abrardev99) [reply tests/ManualModeTest.php:19]: > Do we need this? And the createUsersTable() call below

Not really. But it makes sure the database connection is created and can be used, actually.

Comment (abrardev99) [reply tests/ManualModeTest.php:19]: > Do we need this? And the createUsersTable() call below

Without this, the below assertion got failed. Because tenant connection is not actually used so it's not in the connections class yet. 
```php
expect(array_keys(app('db')->getConnections()))->toBe(['central', 'tenant']);
```
Removing this doesn't effect much but it's extra check which is good to keep.

Comment (stancl) [reply tests/ManualModeTest.php:19]: I see. Then just add a comment explaining that it's to trigger the creation of the `'tenant'` connection.

**Comment by stancl** [comment]
The PR looks great now, thanks for working on this!
