### PR TITLE
Fix initialize() method

### LINKED ISSUE #481: Calls to initialize with a non object value only works the first time it's called
#### Describe the bug
The new feature to initialize the tenant manuall,  passing a string or int, only works the first time it's called. Subsequent calls will throw an error as $tenant->getTenantKey() does not exist.

https://github.com/stancl/tenancy/blob/1ff82fb2a09dd0ee545fd13679aa739ea589dfed/src/Tenancy.php#L34-L36

#### Steps to reproduce
Access the laravel console and try to initialize the tenancy more than once for the same or different tenant by its id:

```php
tenancy()->initialize('tenant1');
tenancy()->initialize('tenant2');
```

#### Expected behavior
The new tenant context would be loaded without throwing an error. In case of the id belongs to the current tenant, nothing should happen.

#### Your setup
 - Laravel version: 7.25.0
 - stancl/tenancy version: 3.1.7

### PR DESCRIPTION
**Pull request by stancl**
Fixes #481

### CODE REVIEW

File: src/Tenancy.php [hunk 1]
```diff
@@ -31,6 +31,16 @@ class Tenancy
      */
     public function initialize($tenant): void
     {
+        if (! is_object($tenant)) {
+            $tenant = $tenant;
```
Comment (lcdss) [inline src/Tenancy.php:35]: This line it's not doing nothing and can be removed.

Comment (lcdss) [inline src/Tenancy.php]: This line is doing nothing and can be removed.

**Review by lcdss — COMMENTED** [review]
I updated the package in my project and didn't find anything wrong. It's only missing a test for this feature.

File: src/Tenancy.php (hunk 1 above)
Comment (stancl) [reply src/Tenancy.php]: Nice catch. So this all works now?
